build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  image: electronuserland/builder:wine
  stage: build
  script:
    - cd angular
    - npm install
    - npm run build
    - cd ..
    - npm install
    - GH_TOKEN=$GH_TOKEN npm run build
    - GH_TOKEN=$GH_TOKEN npm run buildforwindows
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - angular/node_modules/
  only:
    - master